apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: driver-dashboard-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
  labels:
    app: f1-platform
    component: dash
spec:
  tls:
    - hosts:
      - academy.f1-platform.zawalich.pl
      secretName: echo-tls
  rules:
    - host: academy.f1-platform.zawalich.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: driver-dashboard-service
                port:
                  number: 5005