apiVersion: v1
kind: Service
metadata:
  name: driver-dashboard-service
  namespace: f1-platform
spec:
  type: NodePort
  selector:
    app: driver-dashboard-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5005
      name: http